/* groovylint-disable CompileStatic */
//Imports

// ================ Globals ================ //
    // ======== GregTech Recipemaps ======== //
        alloy                  = recipemap('alloy_smelter') 
        arc                    = recipemap('arc_furnace') 
        assembler              = recipemap('assembler')
        assline                = recipemap('assembly_line')
        autoclave              = recipemap('autoclave')
        bender                 = recipemap('bender')
        brewery                = recipemap('brewery')
        canner                 = recipemap('canner')
        centrifuge             = recipemap('centrifuge')
        chembath               = recipemap('chemical_bath')
        chemreactor            = recipemap('chemical_reactor')
        circuitassembler       = recipemap('circuit_assembler')
        cokeoven               = recipemap('coke_oven')
        compressor             = recipemap('compressor')
        cracker                = recipemap('cracker')
        cutter                 = recipemap('cutter')
        distillation           = recipemap('distillation_tower')
        distillery             = recipemap('distillery')
        ebf                    = recipemap('electric_blast_furnace')
        efurnace               = recipemap('electric_furnace')
        electrolyzer           = recipemap('electrolyzer')
        separator              = recipemap('electromagnetic_separator')
        extractor              = recipemap('extractor')
        extruder               = recipemap('extruder')
        fermenter              = recipemap('fermenter')
        heater                 = recipemap('fluid_heater')
        solidifier             = recipemap('fluid_solidifier')
        hammer                 = recipemap('forge_hammer')
        press                  = recipemap('forming_press')
        reactor                = recipemap('fusion_reactor')
        gascollector           = recipemap('gas_collector')
        implosion              = recipemap('implosion_compressor')
        lcr                    = recipemap('large_chemical_reactor')
        laserengraver          = recipemap('laser_engraver')
        lathe                  = recipemap('lathe')
        macerator              = recipemap('macerator')
        massfab                = recipemap('mass_fabricator')
        mixer                  = recipemap('mixer')
        washer                 = recipemap('ore_washer')
        packager               = recipemap('packer')
        polarizer              = recipemap('polarizer')
        pbf                    = recipemap('primitive_blast_furnace')
        pyrolyse               = recipemap('pyrolyse_oven')
        replicator             = recipemap('replicator')
        scanner                = recipemap('scanner')
        sifter                 = recipemap('sifter')
        thermalcentrifuge      = recipemap('thermal_centrifuge')
        freezer                = recipemap('vacuum_freezer')
        wiremill               = recipemap('wiremill')
        combustiongen          = recipemap('combustion_generator')
        gasgen                 = recipemap('gas_turbine')
        plasmagen              = recipemap('plasma_turbine')
        semigen                = recipemap('semi_fluid_generator')
        steamgen               = recipemap('steam_turbine')
        excavator              = recipemap('excavator')
        fcompressor            = recipemap('fluidcompressor')
    // ======== GregTech Recipemaps ======== //
        circuit1 = metaitem('circuit.integrated').withNbt([Configuration: 1])
        circuit2 = metaitem('circuit.integrated').withNbt([Configuration: 2])
        gtsaw = ore('gtSaw')
        gthammer = ore('gtHammer')
        gtwrench = ore('gtWrench')
        gtfile = ore('gtFile')
        gtscrewdriver = ore('gtScrewdriver')
        gtmortar = ore('gtMortar')
        gtwirecutter = ore('gtWirecutter')
        gtknife = ore('gtKnife')
// ================ Globals ================ //