mods.jei.category.hideCategory("actuallyadditions.coffee")
mods.jei.category.hideCategory("actuallyadditions.compost")
mods.jei.category.hideCategory("actuallyadditions.crushing")
mods.jei.category.hideCategory("actuallyadditions.reconstructor")
mods.jei.category.hideCategory("actuallyadditions.empowerer")
mods.jei.category.hideCategory("integrateddynamicscompat:dryingBasin")
mods.jei.category.hideCategory("integrateddynamicscompat:squeezer")
mods.jei.category.hideCategory("integrateddynamicscompat:mechanicalDryingBasin")
mods.jei.category.hideCategory("integrateddynamicscompat:mechanicalSqueezer")
mods.jei.category.hideCategory("zmaster587.AR.rollingMachine")
mods.jei.category.hideCategory("zmaster587.AR.lathe")
mods.jei.category.hideCategory("zmaster587.AR.precisionAssembler")
mods.jei.category.hideCategory("zmaster587.AR.sawMill")
mods.jei.category.hideCategory("zmaster587.AR.chemicalReactor")
mods.jei.category.hideCategory("zmaster587.AR.crystallizer")
mods.jei.category.hideCategory("zmaster587.AR.electrolyzer")
mods.jei.category.hideCategory("zmaster587.AR.arcFurnace")
mods.jei.category.hideCategory("zmaster587.AR.platePresser")
mods.jei.category.hideCategory("zmaster587.AR.centrifuge")
mods.jei.category.hideCategory("zmaster587.AR.precisionlaseretcher")


